### ISSUE TITLE
[LWRP] Multiple cameras + Render Texture causes uGUI disappears on iOS

### ISSUE THREAD

**Issue by beinteractive** [Unity-Technologies/ScriptableRenderPipeline#1161] opened 2018-04-09 08:16 UTC
Setup a scene like the following:
  - Camera A
    - Depth: -1
    - Target: Render Texture
  - Camera B
    - Depth: 0
    - Target: Screen
  - Canvas
    - Render Mode: Screen Space Camera B

Run this scene on iOS, uGUI is not rendered on a screen. This issue is not happened in Editor.

<img width="300" alt="Editor" src="https://user-images.githubusercontent.com/1482297/38486763-ee8006c4-3c18-11e8-9188-0d724d87f75f.png"><img width="300" alt="iOS" src="https://user-images.githubusercontent.com/1482297/38486771-f2c6e84c-3c18-11e8-8403-6dfd47a9aee8.PNG">

See this minimal reproduction project:
https://github.com/beinteractive/LWRP-DisappearingUGUIIssue

As a result of seeing Frame Debugger, `Canvas.RenderSubBatch` is not pushed on the command buffer.

<img width="236" alt="Editor" src="https://user-images.githubusercontent.com/1482297/38486876-452179c2-3c19-11e8-9593-6f7142316c0f.png"> <img width="244" alt="iOS" src="https://user-images.githubusercontent.com/1482297/38486875-44f838dc-3c19-11e8-9c7c-afb05920caf0.png">

Reproduced in:
Unity 2018.1.0b13 + Lightweight Render Pipeline 1.1.2-preview
iOS on any iOS device

**Comment by phi-lira** [comment] 2018-04-18 10:46
Hi. This issue got scheduled to be fixed in the next package version. I'll look into it sometime next week and tag a PR with a fix here so you don't have to wait for the package.

**Comment by mihakrajnc** [comment] 2018-05-05 09:09
Any news on this issue?

**Comment by sebastienlagarde** [comment] 2018-05-07 07:04
Poke @phi-lira

**Comment by phi-lira** [comment] 2018-05-08 09:25
Hey, I'm sorry. This seems an issue on the SRP/engine side. It might take a little longer to get a fix for this.

**Comment by unity3d-kr** [comment] 2018-05-24 10:30
I have same bug on Android.

**Comment by unity3d-kr** [comment] 2018-05-25 01:51
I have same error in Android.
test:
1. raw image set to main camera target texture.
2. make new camera and it set to canvas render camera.
3. raw image draw on canvas.
 raw image show in Editor. it don't show in Android, IOS.

**Comment by gametroopers** [comment] 2018-05-31 09:00
@phi-lira Any update or workaround on this?
We have a project using LWRP that needs to be released soon and that can be an issue :(

**Comment by starloop-xavierarias** [comment] 2018-05-31 09:04
@phi-lira Any update or workaround on this?
We have a project using LWRP that needs to be released soon and that can be an issue :(

**Comment by aleks01010101** [comment] 2018-06-01 09:04
Hi!
I'm looking into this issue right now, hopefully will have something for you soon :)

**Comment by aleks01010101** [comment] 2018-06-01 11:49
A temporary workaround would be to have the canvas rendered in Screen Space - Overlay mode, if that's acceptable. This one seems to work.

**Comment by Immudelki** [comment] 2018-06-20 12:34
Not sure if I made a duplicate here :/ https://github.com/Unity-Technologies/ScriptableRenderPipeline/issues/1575
But I think that I'm basically experiencing the same issue @_@

**Comment by tmthomsen** [comment] 2018-06-26 07:54
We have the same problem. Works fine in editor, but black screen in Android build.
The "Screen Space - Overlay" mode is also a no-go for us, so at the moment our only solution is to not use LWRP.
Is there any progress in fixing this issue?

**Comment by aleks01010101** [comment] 2018-06-28 11:11
hi!
yes, we figured out that the problem is deeper
perhaps @phi-lira has some info on the ETA

**Comment by phi-lira** [comment] 2018-06-29 09:29
Hey guys, I'm sorry for the delay. We are going to resume QA work on LWRP next week. I'm looking at all issues both here and issue tracker.

**Comment by onlinefrog** [comment] 2018-07-03 01:29
hey! just chiming in for a fix for this bug. I've been watching this thread for a couple of months now, heh.  no UI in windows builds right now is rough!
I'm glad progress is being made, looking forward for this bug getting squished :  )

**Comment by phi-lira** [comment] 2018-07-09 15:36
Hey, just to give an update on this issue. I've looked into it and we are discussing a proper solution. It's an issue in core SRP and it's related to UI lifecycle. I'm prototyping something at the moment.

**Comment by FlorinUnity** [comment] 2018-07-10 11:40
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-multiple-cameras-plus-render-texture-causes-ugui-disappears-on-ios

**Closed** 2018-07-11 07:16 UTC
Labels: lwrp
