### ISSUE TITLE
[LWRP] NullReferenceException thrown from HDReflectionProbeEditor when using LWRP

### ISSUE THREAD

**Issue by equalsequals** [Unity-Technologies/ScriptableRenderPipeline#1284] opened 2018-04-26 15:34 UTC
I have a project with the SRP Git Repo 2018.1 branch, so it contains code for both LWRD and HDRP. I currently have LWRP set as my active ScriptableRenderPipeline in my Graphics Settings, but upon selecting a Reflection Probe in a Scene the console gets spammed with a NullReferenceException from UnityEditor.Experimental.Rendering.HDReflectionProbeEditor.Gizmos_Influence.

Here is the provided exception and stack:

> NullReferenceException: Object reference not set to an instance of an object
> UnityEditor.Experimental.Rendering.HDReflectionProbeEditor.Gizmos_Influence (UnityEngine.ReflectionProbe p, UnityEngine.Experimental.Rendering.HDAdditionalReflectionData a, UnityEditor.Editor e, Boolean isEdit) (at Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRP/Editor/Lighting/Reflection/HDReflectionProbeEditor.Handles.cs:399)
> UnityEditor.Experimental.Rendering.HDReflectionProbeEditor.DrawSelectedGizmo (UnityEngine.ReflectionProbe reflectionProbe, GizmoType gizmoType) (at Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRP/Editor/Lighting/Reflection/HDReflectionProbeEditor.Handles.cs:320)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by sebastienlagarde** [comment] 2018-05-07 07:02
@RemyUnity can you check? Thanks

**Comment by RemyUnity** [comment] 2018-05-31 07:52
@equalsequals Thanks for reporting. I can confirm that this bugs still happens in the 2018.1 branch, and also in the released packages.
Also, note that you don't need to have LWRP, you can simply have no RP assigned while HDRP is in your project, the error will be thrown.

**Comment by RemyUnity** [comment] 2018-05-31 08:57
Issue Tracker link : https://issuetracker.unity3d.com/issues/hdrp-2018-dot-1-nullreferenceexception-thrown-from-hdreflectionprobeeditor-when-not-using-hdrp

**Comment by RemyUnity** [comment] 2018-05-31 08:58
@equalsequals I checked in the 2018.1-experimental branch, and the issue is fixed there.

**Closed** 2018-06-22 10:31 UTC
Labels: HDRP, lwrp
